// Code generated by protoc-gen-go.
// source: beaconCloud/rpcServer/user-srv/proto/account/account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	beaconCloud/rpcServer/user-srv/proto/account/account.proto

It has these top-level messages:
	User
	Session
	GetUserAccountRequest
	GetUserAccountResponse
	ReadAccountRequest
	ReadAccountResponse
	RetrievePasswordRequest
	RetrievePasswordResponse
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	UpdatePasswordRequest
	UpdatePasswordResponse
	SearchRequest
	SearchResponse
	ReadSessionRequest
	ReadSessionResponse
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NodeId   string `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Created  int64  `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated  int64  `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
	Password string `protobuf:"bytes,7,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Session struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Created  int64  `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Expires  int64  `protobuf:"varint,4,opt,name=expires" json:"expires,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetUserAccountRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *GetUserAccountRequest) Reset()                    { *m = GetUserAccountRequest{} }
func (m *GetUserAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserAccountRequest) ProtoMessage()               {}
func (*GetUserAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetUserAccountResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserAccountResponse) Reset()                    { *m = GetUserAccountResponse{} }
func (m *GetUserAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserAccountResponse) ProtoMessage()               {}
func (*GetUserAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserAccountResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ReadAccountRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadAccountRequest) Reset()                    { *m = ReadAccountRequest{} }
func (m *ReadAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAccountRequest) ProtoMessage()               {}
func (*ReadAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReadAccountResponse struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NodeId  string `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	NodeUrl string `protobuf:"bytes,3,opt,name=nodeUrl" json:"nodeUrl,omitempty"`
}

func (m *ReadAccountResponse) Reset()                    { *m = ReadAccountResponse{} }
func (m *ReadAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadAccountResponse) ProtoMessage()               {}
func (*ReadAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RetrievePasswordRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RetrievePasswordRequest) Reset()                    { *m = RetrievePasswordRequest{} }
func (m *RetrievePasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrievePasswordRequest) ProtoMessage()               {}
func (*RetrievePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RetrievePasswordResponse struct {
}

func (m *RetrievePasswordResponse) Reset()                    { *m = RetrievePasswordResponse{} }
func (m *RetrievePasswordResponse) String() string            { return proto.CompactTextString(m) }
func (*RetrievePasswordResponse) ProtoMessage()               {}
func (*RetrievePasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type CreateRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type ReadResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type UpdatePasswordRequest struct {
	UserId          string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	OldPassword     string `protobuf:"bytes,2,opt,name=oldPassword" json:"oldPassword,omitempty"`
	NewPassword     string `protobuf:"bytes,3,opt,name=newPassword" json:"newPassword,omitempty"`
	ConfirmPassword string `protobuf:"bytes,4,opt,name=confirmPassword" json:"confirmPassword,omitempty"`
}

func (m *UpdatePasswordRequest) Reset()                    { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()               {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type UpdatePasswordResponse struct {
}

func (m *UpdatePasswordResponse) Reset()                    { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()               {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type SearchRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type SearchResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReadSessionRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
}

func (m *ReadSessionRequest) Reset()                    { *m = ReadSessionRequest{} }
func (m *ReadSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadSessionRequest) ProtoMessage()               {}
func (*ReadSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ReadSessionResponse struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
}

func (m *ReadSessionResponse) Reset()                    { *m = ReadSessionResponse{} }
func (m *ReadSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadSessionResponse) ProtoMessage()               {}
func (*ReadSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ReadSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type LoginResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LogoutRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type LogoutResponse struct {
}

func (m *LogoutResponse) Reset()                    { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()               {}
func (*LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Session)(nil), "Session")
	proto.RegisterType((*GetUserAccountRequest)(nil), "GetUserAccountRequest")
	proto.RegisterType((*GetUserAccountResponse)(nil), "GetUserAccountResponse")
	proto.RegisterType((*ReadAccountRequest)(nil), "ReadAccountRequest")
	proto.RegisterType((*ReadAccountResponse)(nil), "ReadAccountResponse")
	proto.RegisterType((*RetrievePasswordRequest)(nil), "RetrievePasswordRequest")
	proto.RegisterType((*RetrievePasswordResponse)(nil), "RetrievePasswordResponse")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "UpdatePasswordResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*ReadSessionRequest)(nil), "ReadSessionRequest")
	proto.RegisterType((*ReadSessionResponse)(nil), "ReadSessionResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "LogoutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for LoginDbInf service

type LoginDbInfClient interface {
	GetUserByAccount(ctx context.Context, in *GetUserAccountRequest, opts ...client.CallOption) (*GetUserAccountResponse, error)
	ReadAccountRoute(ctx context.Context, in *ReadAccountRequest, opts ...client.CallOption) (*ReadAccountResponse, error)
}

type loginDbInfClient struct {
	c           client.Client
	serviceName string
}

func NewLoginDbInfClient(serviceName string, c client.Client) LoginDbInfClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "logindbinf"
	}
	return &loginDbInfClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *loginDbInfClient) GetUserByAccount(ctx context.Context, in *GetUserAccountRequest, opts ...client.CallOption) (*GetUserAccountResponse, error) {
	req := c.c.NewRequest(c.serviceName, "LoginDbInf.GetUserByAccount", in)
	out := new(GetUserAccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginDbInfClient) ReadAccountRoute(ctx context.Context, in *ReadAccountRequest, opts ...client.CallOption) (*ReadAccountResponse, error) {
	req := c.c.NewRequest(c.serviceName, "LoginDbInf.ReadAccountRoute", in)
	out := new(ReadAccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoginDbInf service

type LoginDbInfHandler interface {
	GetUserByAccount(context.Context, *GetUserAccountRequest, *GetUserAccountResponse) error
	ReadAccountRoute(context.Context, *ReadAccountRequest, *ReadAccountResponse) error
}

func RegisterLoginDbInfHandler(s server.Server, hdlr LoginDbInfHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&LoginDbInf{hdlr}, opts...))
}

type LoginDbInf struct {
	LoginDbInfHandler
}

func (h *LoginDbInf) GetUserByAccount(ctx context.Context, in *GetUserAccountRequest, out *GetUserAccountResponse) error {
	return h.LoginDbInfHandler.GetUserByAccount(ctx, in, out)
}

func (h *LoginDbInf) ReadAccountRoute(ctx context.Context, in *ReadAccountRequest, out *ReadAccountResponse) error {
	return h.LoginDbInfHandler.ReadAccountRoute(ctx, in, out)
}

// Client API for Account service

type AccountClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...client.CallOption) (*UpdatePasswordResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error)
	ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...client.CallOption) (*ReadSessionResponse, error)
	RetrievePassword(ctx context.Context, in *RetrievePasswordRequest, opts ...client.CallOption) (*RetrievePasswordResponse, error)
}

type accountClient struct {
	c           client.Client
	serviceName string
}

func NewAccountClient(serviceName string, c client.Client) AccountClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "account"
	}
	return &accountClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...client.CallOption) (*UpdatePasswordResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.UpdatePassword", in)
	out := new(UpdatePasswordResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Logout", in)
	out := new(LogoutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...client.CallOption) (*ReadSessionResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.ReadSession", in)
	out := new(ReadSessionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) RetrievePassword(ctx context.Context, in *RetrievePasswordRequest, opts ...client.CallOption) (*RetrievePasswordResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.RetrievePassword", in)
	out := new(RetrievePasswordResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	UpdatePassword(context.Context, *UpdatePasswordRequest, *UpdatePasswordResponse) error
	Login(context.Context, *LoginRequest, *LoginResponse) error
	Logout(context.Context, *LogoutRequest, *LogoutResponse) error
	ReadSession(context.Context, *ReadSessionRequest, *ReadSessionResponse) error
	RetrievePassword(context.Context, *RetrievePasswordRequest, *RetrievePasswordResponse) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Account{hdlr}, opts...))
}

type Account struct {
	AccountHandler
}

func (h *Account) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.AccountHandler.Create(ctx, in, out)
}

func (h *Account) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.AccountHandler.Read(ctx, in, out)
}

func (h *Account) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.AccountHandler.Update(ctx, in, out)
}

func (h *Account) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.AccountHandler.Delete(ctx, in, out)
}

func (h *Account) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.AccountHandler.Search(ctx, in, out)
}

func (h *Account) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, out *UpdatePasswordResponse) error {
	return h.AccountHandler.UpdatePassword(ctx, in, out)
}

func (h *Account) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.AccountHandler.Login(ctx, in, out)
}

func (h *Account) Logout(ctx context.Context, in *LogoutRequest, out *LogoutResponse) error {
	return h.AccountHandler.Logout(ctx, in, out)
}

func (h *Account) ReadSession(ctx context.Context, in *ReadSessionRequest, out *ReadSessionResponse) error {
	return h.AccountHandler.ReadSession(ctx, in, out)
}

func (h *Account) RetrievePassword(ctx context.Context, in *RetrievePasswordRequest, out *RetrievePasswordResponse) error {
	return h.AccountHandler.RetrievePassword(ctx, in, out)
}

func init() {
	proto.RegisterFile("beaconCloud/rpcServer/user-srv/proto/account/account.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0xb6, 0xf3, 0xdb, 0x4e, 0x1b, 0x27, 0xda, 0xb6, 0xa9, 0xeb, 0x73, 0x8e, 0x4e, 0xb4, 0x02,
	0x29, 0x14, 0x75, 0x23, 0xa5, 0x57, 0xf4, 0x06, 0x41, 0x8b, 0x50, 0x24, 0x2e, 0x4a, 0xaa, 0x8a,
	0x1b, 0x6e, 0xdc, 0x78, 0x03, 0x96, 0x12, 0x6f, 0xb0, 0x9d, 0x16, 0x9e, 0x80, 0x17, 0xe0, 0x96,
	0x77, 0xe0, 0x11, 0xd1, 0xfe, 0x25, 0xde, 0x4d, 0x42, 0x23, 0xae, 0xda, 0x99, 0xfd, 0x66, 0x67,
	0x76, 0x66, 0xbe, 0xcf, 0x81, 0x8b, 0x3b, 0x1a, 0x8e, 0x58, 0x72, 0x39, 0x61, 0xf3, 0xa8, 0x97,
	0xce, 0x46, 0x37, 0x34, 0xbd, 0xa7, 0x69, 0x6f, 0x9e, 0xd1, 0xf4, 0x2c, 0x4b, 0xef, 0x7b, 0xb3,
	0x94, 0xe5, 0xac, 0x17, 0x8e, 0x46, 0x6c, 0x9e, 0xe4, 0xfa, 0x2f, 0x11, 0x5e, 0xfc, 0xcb, 0x85,
	0xca, 0x6d, 0x46, 0x53, 0xe4, 0x41, 0x29, 0x8e, 0x7c, 0xb7, 0xe3, 0x76, 0x77, 0x87, 0xa5, 0x38,
	0x42, 0x6d, 0xa8, 0x25, 0x2c, 0xa2, 0x83, 0xc8, 0x2f, 0x09, 0x9f, 0xb2, 0x50, 0x00, 0x3b, 0xfc,
	0xe2, 0x24, 0x9c, 0x52, 0xbf, 0x2c, 0x4e, 0x16, 0x36, 0x3a, 0x84, 0x2a, 0x9d, 0x86, 0xf1, 0xc4,
	0xaf, 0x88, 0x03, 0x69, 0x20, 0x1f, 0xea, 0xa3, 0x94, 0x86, 0x39, 0x8d, 0xfc, 0x6a, 0xc7, 0xed,
	0x96, 0x87, 0xda, 0xe4, 0x27, 0xf3, 0x59, 0x24, 0x4e, 0x6a, 0xf2, 0x44, 0x99, 0x3c, 0xcb, 0x2c,
	0xcc, 0xb2, 0x07, 0x96, 0x46, 0x7e, 0x5d, 0x66, 0xd1, 0x36, 0x8e, 0xa1, 0x7e, 0x43, 0xb3, 0x2c,
	0x66, 0xc9, 0x4a, 0xd1, 0xc5, 0xe2, 0x4a, 0x56, 0x71, 0x85, 0x32, 0xca, 0x2b, 0x65, 0xd0, 0xaf,
	0xb3, 0x38, 0xa5, 0x99, 0x28, 0xbc, 0x3c, 0xd4, 0x26, 0x3e, 0x87, 0xa3, 0xb7, 0x34, 0xe7, 0xfd,
	0x79, 0x25, 0xbb, 0x36, 0xa4, 0x5f, 0xe6, 0x34, 0xcb, 0x8d, 0x44, 0xae, 0x99, 0x08, 0x9f, 0x43,
	0xdb, 0x0e, 0xca, 0x66, 0x2c, 0xc9, 0x28, 0x3a, 0x81, 0x0a, 0x47, 0x89, 0x88, 0xbd, 0x7e, 0x95,
	0x70, 0xcc, 0x50, 0xb8, 0xf0, 0x13, 0x40, 0x43, 0x1a, 0x46, 0x56, 0x1a, 0xeb, 0x7d, 0xf8, 0x03,
	0x1c, 0x18, 0x28, 0x75, 0xef, 0xb6, 0xb3, 0xf3, 0xa1, 0xce, 0xff, 0xbb, 0x4d, 0x27, 0x6a, 0x74,
	0xda, 0xc4, 0xef, 0xe1, 0x78, 0x48, 0xf3, 0x34, 0xa6, 0xf7, 0xf4, 0x5a, 0xf5, 0x79, 0x8b, 0xa7,
	0x1a, 0x63, 0x2a, 0x59, 0x63, 0x0a, 0xc0, 0x5f, 0xbd, 0x52, 0x16, 0x8c, 0x4f, 0xa1, 0x71, 0x29,
	0x9a, 0xaf, 0x93, 0xfc, 0xa1, 0x33, 0x2d, 0xf0, 0x34, 0x56, 0x45, 0xff, 0x0f, 0x8d, 0x2b, 0x3a,
	0xa1, 0xcb, 0x68, 0xbb, 0x4d, 0x2d, 0xf0, 0x34, 0x40, 0x85, 0xfc, 0x07, 0x7b, 0xbc, 0x71, 0x9b,
	0x02, 0x9e, 0xc1, 0xbe, 0x3c, 0x7e, 0x7c, 0x50, 0xa7, 0xd0, 0xb8, 0x15, 0x4b, 0xba, 0x5d, 0xe9,
	0x1a, 0xab, 0xea, 0xf8, 0xe9, 0xc2, 0x91, 0x74, 0xd9, 0x6d, 0x6e, 0x43, 0x8d, 0xc7, 0x0c, 0x74,
	0x59, 0xca, 0x42, 0x1d, 0xd8, 0x63, 0x93, 0xe8, 0xda, 0xec, 0x72, 0xd1, 0xc5, 0x11, 0x09, 0x7d,
	0x58, 0x20, 0xe4, 0x64, 0x8b, 0x2e, 0xd4, 0x85, 0xe6, 0x88, 0x25, 0xe3, 0x38, 0x9d, 0x2e, 0x50,
	0x92, 0xa1, 0xb6, 0x1b, 0xfb, 0xd0, 0xb6, 0xcb, 0x53, 0x95, 0x33, 0x68, 0xdc, 0xd0, 0x30, 0x1d,
	0x7d, 0xde, 0x66, 0x2f, 0x16, 0x42, 0x50, 0x2a, 0x0a, 0xc1, 0x21, 0x54, 0x27, 0xf1, 0x34, 0xce,
	0x15, 0xff, 0xa4, 0xc1, 0x1f, 0xce, 0xc6, 0xe3, 0x8c, 0xe6, 0x8a, 0x7c, 0xca, 0xc2, 0x67, 0xe0,
	0xe9, 0x84, 0x6a, 0x2a, 0xff, 0x40, 0x95, 0x67, 0xc8, 0x7c, 0xb7, 0x53, 0x5e, 0xb6, 0x5a, 0xfa,
	0x70, 0x5f, 0x12, 0x48, 0x29, 0x83, 0x2e, 0xf2, 0x5f, 0xd8, 0xcd, 0xa4, 0x67, 0xd1, 0xd8, 0xa5,
	0x03, 0xbf, 0x90, 0x74, 0x5a, 0xc4, 0xa8, 0x3c, 0x18, 0xea, 0x0a, 0xa3, 0x86, 0xba, 0x43, 0x34,
	0x44, 0x1f, 0xe0, 0x8f, 0xb0, 0xff, 0x8e, 0x7d, 0x8a, 0x93, 0xbf, 0xef, 0x46, 0x91, 0x3b, 0x65,
	0x8b, 0x3b, 0xa7, 0xd0, 0x50, 0xb7, 0x3f, 0xbe, 0x90, 0x67, 0x02, 0xcb, 0xe6, 0xf9, 0x76, 0x6f,
	0x6e, 0x81, 0xa7, 0xe1, 0xf2, 0xee, 0xfe, 0x0f, 0x17, 0x60, 0xc2, 0xb3, 0x5d, 0xdd, 0x0d, 0x92,
	0x31, 0x7a, 0x03, 0x2d, 0x25, 0x5f, 0xaf, 0xbf, 0x29, 0xa1, 0x41, 0x6d, 0xb2, 0x56, 0x06, 0x83,
	0x63, 0xb2, 0x5e, 0xe9, 0xb0, 0x83, 0x5e, 0x42, 0xab, 0x28, 0x55, 0x6c, 0x9e, 0x53, 0x74, 0x40,
	0x56, 0x35, 0x2e, 0x38, 0x24, 0x6b, 0x24, 0x0d, 0x3b, 0xfd, 0xef, 0x15, 0xa8, 0xeb, 0xfc, 0xcf,
	0xa1, 0x26, 0x35, 0x00, 0x79, 0xc4, 0x10, 0x8e, 0xa0, 0x49, 0x2c, 0x71, 0x70, 0xd0, 0x53, 0xa8,
	0xf0, 0x1b, 0xd1, 0x3e, 0x29, 0x50, 0x3e, 0x68, 0x90, 0x22, 0xc3, 0xb1, 0xc3, 0xef, 0x94, 0xab,
	0x8e, 0x3c, 0x62, 0x30, 0x3a, 0x68, 0x12, 0x8b, 0xb5, 0x02, 0x2c, 0x15, 0x05, 0x79, 0xc4, 0xd0,
	0x9e, 0xa0, 0x49, 0x2c, 0xa9, 0x11, 0x60, 0xb9, 0xb9, 0xc8, 0x23, 0x06, 0x67, 0x82, 0x26, 0x31,
	0x57, 0x1a, 0x3b, 0xe8, 0x52, 0x6b, 0xc4, 0x82, 0xad, 0x6d, 0xb2, 0x56, 0x21, 0x82, 0x63, 0xb2,
	0x81, 0x9a, 0x0e, 0xea, 0x42, 0x55, 0xec, 0x0b, 0x6a, 0x90, 0xe2, 0x56, 0x06, 0x1e, 0x31, 0xd6,
	0x48, 0xd6, 0x26, 0xc7, 0x8f, 0xc4, 0xd9, 0x72, 0x6d, 0x82, 0x26, 0x31, 0xf7, 0x02, 0x3b, 0xe8,
	0x42, 0xaa, 0xa6, 0xfe, 0xda, 0xca, 0xf1, 0x99, 0x0c, 0x53, 0xe3, 0xb3, 0x28, 0x84, 0x1d, 0x34,
	0xe0, 0xf3, 0x37, 0xe5, 0x1f, 0xf9, 0x64, 0xc3, 0x47, 0x26, 0x38, 0x21, 0x1b, 0xbf, 0x15, 0xce,
	0x5d, 0x4d, 0xfc, 0x54, 0x39, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x29, 0xfd, 0x4b, 0x66, 0xe8,
	0x08, 0x00, 0x00,
}
